# Generated by Django 3.0.8 on 2020-07-25 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consorcio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Consorcio')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_proyecto', models.CharField(max_length=20, verbose_name='Código de Proyecto')),
                ('cod_snip', models.CharField(default='', max_length=20, verbose_name='Código Snip')),
                ('denominacion', models.TextField(verbose_name='Denominación')),
                ('denominacion_corta', models.TextField(verbose_name='Denominación Corta')),
                ('nivel', models.CharField(max_length=30, verbose_name='Nivel')),
                ('funcion', models.CharField(max_length=30, verbose_name='Funcion')),
                ('fase', models.CharField(max_length=50, verbose_name='Fase')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('taxonomia', models.CharField(max_length=100, verbose_name='Taxonomía')),
                ('situacion', models.CharField(max_length=100, verbose_name='Situación')),
                ('fecha_estado', models.DateField(verbose_name='Fecha de Estado')),
                ('fecha_registro', models.DateField(verbose_name='Fecha de Registro')),
                ('activo', models.BooleanField(verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Consorcio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(null=True, verbose_name='Fecha de Fin')),
                ('vigente', models.BooleanField(verbose_name='Vigente')),
                ('telefono', models.CharField(max_length=30, verbose_name='Número de celular')),
                ('jefe', models.BooleanField(verbose_name='Jefe')),
                ('costo', models.FloatField(default=0, verbose_name='Costo')),
                ('consorcio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Consorcio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Personal_Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(null=True, verbose_name='Fecha de Fin')),
                ('vigente', models.BooleanField(verbose_name='Vigente')),
                ('telefono', models.CharField(max_length=30, verbose_name='Número de celular')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('proyecto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Proyecto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='consorcio',
            name='proyecto_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.Proyecto'),
        ),
    ]
