# Generated by Django 3.0.8 on 2020-07-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200726_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_cliente',
            name='codigo',
            field=models.CharField(max_length=8, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='personal_consorcio',
            name='codigo',
            field=models.CharField(max_length=8, null=True, unique=True, verbose_name='Código'),
        ),
    ]
