# Generated by Django 3.0.8 on 2020-07-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200726_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_cliente',
            name='codigo',
            field=models.CharField(default='', max_length=8, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='personal_consorcio',
            name='codigo',
            field=models.CharField(default='', max_length=8, unique=True, verbose_name='Código'),
        ),
    ]
